# Generated by Django 3.2 on 2021-06-10 05:02

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content_markdown', models.TextField(null=True)),
                ('content_rendered', models.TextField(null=True)),
                ('note_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('column', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='boards.column')),
                ('labels', models.ManyToManyField(related_name='notes', to='boards.Label')),
            ],
            options={
                'ordering': ['note_order'],
            },
        ),
    ]
