# Generated by Django 3.2 on 2021-06-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['task_order']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_order',
            new_name='task_order',
        ),
    ]
